In [1]:
import warnings
warnings.filterwarnings('ignore')

from helper_functions.train_funcs import *


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [10]:
evaluate_model(model_path='Saved\Enhanced_SNN_hd64_lr0.005_wd1e-05_epochs30_seed42_bs16_drop0.3_bn1_best.pt',root_path='he_50_33/',return_predictions=True)

Test Loss: 0.5993, Test Accuracy: 0.8216
Confusion Matrix:
[[36  4  0  0  2  3  1  1  2  1]
 [ 0 94  4  0  0  0  0  0  2  0]
 [ 0  1 95  0  0  0  0  0  1  3]
 [ 1  4  0 47  2  0  3  6 22  1]
 [ 0  0  1  1 63  1 17  0  3  0]
 [ 0  2  0  1  2 92  0  2  1  0]
 [ 0  1  1  3 21  0 44  0 16  0]
 [ 0  4  0  0  1  2  2 90  1  0]
 [ 0  1  3  3  0  0  3  1 89  0]
 [ 0  2  1  0  0  0  0  0  1 96]]


(0.5993477982179872,
 0.8215859030837004,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(7),
  np.int64(0),
  np.int64(0),
  np.int64(9),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(0),
  np.int64(8),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(6),
  np.int64(4),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(8),
  np.int64(4),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1)

In [7]:
evaluate_model(model_path='Saved\Enhanced_SNN_hd64_lr0.005_wd1e-05_epochs30_seed42_bs16_drop0.3_bn1_best.pt',root_path='he_25_05/',return_predictions=True)

Test Loss: 0.5544, Test Accuracy: 0.8205
Confusion Matrix:
[[37  5  0  1  1  4  0  1  1  0]
 [ 0 93  4  0  0  0  0  0  3  0]
 [ 0  3 94  0  0  0  1  0  1  1]
 [ 1  3  0 41  2  0  4  4 31  0]
 [ 0  0  0  1 57  0 20  2  6  0]
 [ 0  0  0  1  3 93  0  2  1  0]
 [ 0  0  2  2 17  0 44  1 20  0]
 [ 0  3  0  0  0  1  2 93  1  0]
 [ 0  1  1  0  0  0  2  0 96  0]
 [ 0  1  1  0  0  0  0  0  1 97]]


(0.5544253802248116,
 0.8204845814977973,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(7),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(1),
  np.int64(1),
  np.int64(0),
  np.int64(3),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(4),
  np.int64(8),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(2),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(8)

In [6]:
evaluate_model(model_path='Saved\Augmented_SNN_hd64_lr0.005_wd1e-05_epochs30_seed42_bs16_drop0.3_bn1_best.pt',root_path='he_25_05/',return_predictions=True)

Test Loss: 0.4126, Test Accuracy: 0.8678
Confusion Matrix:
[[45  1  1  0  1  0  0  0  2  0]
 [ 0 95  1  0  0  0  1  0  3  0]
 [ 0  2 95  1  0  0  0  0  2  0]
 [ 0  0  0 56  2  0 10  5 13  0]
 [ 0  0  0  0 62  1 19  3  1  0]
 [ 0  0  0  0  2 93  1  2  2  0]
 [ 0  0  1  2 18  0 56  3  6  0]
 [ 0  0  0  0  0  0  1 98  1  0]
 [ 0  1  1  6  0  0  2  0 90  0]
 [ 0  0  0  0  1  0  0  0  1 98]]


(0.41257040568723763,
 0.8678414096916299,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(8),
  np.int64(0),
  np.int64(2),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(4),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(8),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(8

In [5]:
evaluate_model(model_path='Saved\Augmented_SNN_hd64_lr0.005_wd1e-05_epochs30_seed42_bs16_drop0.3_bn1_best.pt',root_path='he_25_33/',return_predictions=True)

Test Loss: 0.4583, Test Accuracy: 0.8480
Confusion Matrix:
[[45  1  1  0  1  0  0  0  2  0]
 [ 0 92  2  0  0  0  1  1  4  0]
 [ 0  3 91  2  0  0  1  0  2  1]
 [ 0  0  0 51  2  0 10  6 17  0]
 [ 0  0  1  0 60  1 20  3  1  0]
 [ 0  0  0  0  3 91  1  2  3  0]
 [ 0  1  0  2 18  0 56  2  7  0]
 [ 0  1  0  1  0  0  1 96  1  0]
 [ 0  1  1  5  0  0  1  0 92  0]
 [ 0  0  2  0  1  0  0  0  1 96]]


(0.45834342775673703,
 0.8480176211453745,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(8),
  np.int64(0),
  np.int64(2),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(4),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(8),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(8

In [11]:
evaluate_model(model_path='Saved/Augmented_SNN_hd96_lr0.01_wd1e-05_epochs60_seed42_bs16_drop0.3_bn1_final.pt',root_path='he_10_33/',return_predictions=True)

Test Loss: 0.3634, Test Accuracy: 0.8866
Confusion Matrix:
[[45  2  0  0  0  1  0  1  1  0]
 [ 1 96  1  0  0  0  1  0  1  0]
 [ 0  3 95  0  0  0  0  0  1  1]
 [ 0  1  0 60  0  1  5  4 15  0]
 [ 0  0  0  1 73  1  9  0  2  0]
 [ 0  0  0  0  2 93  1  2  2  0]
 [ 0  0  1  0 23  1 54  0  7  0]
 [ 0  1  0  0  0  0  1 98  0  0]
 [ 0  1  0  6  0  0  0  0 93  0]
 [ 0  0  1  0  0  0  0  0  1 98]]


(0.36343131368530207,
 0.8865638766519823,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(7),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(8),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(8),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(6

In [12]:
evaluate_model(model_path='Saved/Augmented_SNN_hd96_lr0.01_wd1e-05_epochs60_seed42_bs16_drop0.3_bn1_final.pt',root_path='he_10_05/',return_predictions=True)

Test Loss: 0.3209, Test Accuracy: 0.9009
Confusion Matrix:
[[46  2  0  0  0  1  0  0  1  0]
 [ 1 98  0  0  0  0  0  0  1  0]
 [ 0  3 95  0  0  0  0  0  1  1]
 [ 0  1  0 62  0  1  5  4 13  0]
 [ 0  0  0  1 75  1  8  0  1  0]
 [ 0  0  0  0  1 96  1  2  0  0]
 [ 0  0  1  0 22  1 56  0  6  0]
 [ 0  0  0  0  0  0  1 99  0  0]
 [ 0  1  0  6  0  0  0  0 93  0]
 [ 0  0  1  0  0  0  0  0  1 98]]


(0.3208727799998275,
 0.9008810572687225,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(8),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(8),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1)

In [13]:
evaluate_model(model_path='Saved/Augmented_SNN_hd96_lr0.01_wd1e-05_epochs60_seed42_bs16_drop0.3_bn1_final.pt',root_path='he_25_33/',return_predictions=True)

Test Loss: 0.3742, Test Accuracy: 0.8789
Confusion Matrix:
[[44  2  1  0  0  1  1  0  1  0]
 [ 0 98  1  0  0  0  1  0  0  0]
 [ 0  0 98  1  0  0  0  0  0  1]
 [ 0  1  1 58  2  0  5  6 13  0]
 [ 0  0  0  1 72  1 11  0  1  0]
 [ 0  1  0  0  2 93  1  2  1  0]
 [ 0  1  0  0 22  1 55  0  7  0]
 [ 0  1  0  2  0  0  1 96  0  0]
 [ 0  1  2  9  0  0  2  0 86  0]
 [ 0  1  0  0  0  0  0  0  1 98]]


(0.3741938204600893,
 0.8788546255506607,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(2),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(6),
  np.int64(0),
  np.int64(8),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(6)

In [14]:
evaluate_model(model_path='Saved/Augmented_SNN_hd96_lr0.01_wd1e-05_epochs60_seed42_bs16_drop0.3_bn1_final.pt',root_path='he_25_05/',return_predictions=True)

Test Loss: 0.3442, Test Accuracy: 0.8877
Confusion Matrix:
[[44  2  1  0  0  1  1  0  1  0]
 [ 0 98  1  0  0  0  0  0  1  0]
 [ 0  0 99  0  0  0  0  0  0  1]
 [ 0  1  1 60  2  0  5  4 13  0]
 [ 0  0  0  1 73  0 11  0  1  0]
 [ 0  1  0  0  1 95  1  2  0  0]
 [ 0  0  1  0 20  0 57  1  7  0]
 [ 0  1  0  1  0  0  1 97  0  0]
 [ 0  1  3  9  0  0  2  0 85  0]
 [ 0  1  0  0  0  0  0  0  1 98]]


(0.34415773135320893,
 0.8876651982378855,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(2),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(6),
  np.int64(0),
  np.int64(8),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(8

In [15]:
evaluate_model(model_path='Saved/Augmented_SNN_hd96_lr0.01_wd1e-05_epochs60_seed42_bs16_drop0.3_bn1_final.pt',root_path='he_50_33/',return_predictions=True)

Test Loss: 0.4479, Test Accuracy: 0.8535
Confusion Matrix:
[[41  4  0  0  0  1  1  1  0  2]
 [ 0 95  5  0  0  0  0  0  0  0]
 [ 0  1 97  0  0  0  0  0  1  1]
 [ 0  3  0 58  2  0  6  6 11  0]
 [ 0  1  0  0 68  0 15  1  1  0]
 [ 0  1  0  0  2 94  1  2  0  0]
 [ 0  1  0  0 21  1 55  1  7  0]
 [ 0  4  0  0  0  0  1 95  0  0]
 [ 0  2  1 15  0  0  6  0 76  0]
 [ 0  2  0  0  0  0  0  1  1 96]]


(0.44791074187077323,
 0.8535242290748899,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(7),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(9),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(6),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(9),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1

In [16]:
evaluate_model(model_path='Saved/Augmented_SNN_hd96_lr0.01_wd1e-05_epochs60_seed42_bs16_drop0.3_bn1_final.pt',root_path='he_50_05/',return_predictions=True)

Test Loss: 0.4237, Test Accuracy: 0.8689
Confusion Matrix:
[[43  3  0  0  0  1  1  0  0  2]
 [ 0 98  2  0  0  0  0  0  0  0]
 [ 0  1 98  0  0  0  0  0  0  1]
 [ 0  3  0 59  2  0  6  6 10  0]
 [ 0  1  0  0 68  0 15  2  0  0]
 [ 0  1  0  0  2 94  1  2  0  0]
 [ 0  0  0  0 20  1 57  1  7  0]
 [ 0  3  0  0  0  0  1 96  0  0]
 [ 0  1  1 14  0  0  5  1 78  0]
 [ 0  1  0  0  0  0  0  0  1 98]]


(0.42366747667306454,
 0.8689427312775331,
 [np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(9),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(6),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(0),
  np.int64(9),
  np.int64(5),
  np.int64(0),
  np.int64(0),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1),
  np.int64(1